// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjlNxwZInTBFJn_rfUni0RgBPDsBtY9JI',
    appId: '1:453130025109:web:69ffb245c844764102439c',
    messagingSenderId: '453130025109',
    projectId: 'totalxproject-18e83',
    authDomain: 'totalxproject-18e83.firebaseapp.com',
    storageBucket: 'totalxproject-18e83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDneJ5O5KaoKHgsuhVu7IG7FKPyiDBvO4',
    appId: '1:453130025109:android:d3c0ad29284a82d302439c',
    messagingSenderId: '453130025109',
    projectId: 'totalxproject-18e83',
    storageBucket: 'totalxproject-18e83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXdOmkUTEDxw6ZwUjXRnwX8bLwzsYS14g',
    appId: '1:453130025109:ios:d377d2b79254a0ac02439c',
    messagingSenderId: '453130025109',
    projectId: 'totalxproject-18e83',
    storageBucket: 'totalxproject-18e83.firebasestorage.app',
    iosBundleId: 'com.example.totalxproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjlNxwZInTBFJn_rfUni0RgBPDsBtY9JI',
    appId: '1:453130025109:web:f91346d839318fa002439c',
    messagingSenderId: '453130025109',
    projectId: 'totalxproject-18e83',
    authDomain: 'totalxproject-18e83.firebaseapp.com',
    storageBucket: 'totalxproject-18e83.firebasestorage.app',
  );
}
